// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace cz.kruch.track.util {
public class ExtraMath: global::java.lang.Object {
private void @this(){
//XMLVM_BEGIN_WRAPPER[cz.kruch.track.util.ExtraMath: void <init>()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    ((global::java.lang.Object) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[cz.kruch.track.util.ExtraMath: void <init>()]
}

public static int prescale(float n1, int n2){
//XMLVM_BEGIN_WRAPPER[cz.kruch.track.util.ExtraMath: int prescale(float, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1.f = n1;
    _r2.i = n2;
    _r0.f = (float) _r2.i;
    _r0.f = _r0.f * _r1.f;
    _r0.i = global::cz.kruch.track.util.ExtraMath.round((float) _r0.f);
    return _r0.i;
//XMLVM_END_WRAPPER[cz.kruch.track.util.ExtraMath: int prescale(float, int)]
}

public static int descale(float n1, int n2){
//XMLVM_BEGIN_WRAPPER[cz.kruch.track.util.ExtraMath: int descale(float, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1.f = n1;
    _r2.i = n2;
    _r0.f = (float) _r2.i;
    _r0.f = _r0.f / _r1.f;
    _r0.i = global::cz.kruch.track.util.ExtraMath.round((float) _r0.f);
    return _r0.i;
//XMLVM_END_WRAPPER[cz.kruch.track.util.ExtraMath: int descale(float, int)]
}

public static int grade(double n1){
//XMLVM_BEGIN_WRAPPER[cz.kruch.track.util.ExtraMath: int grade(double)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r5.d = n1;
    _r0.i = 1;
    label1:;
    _r1.d = (double) _r0.i;
    _r1.d = _r5.d / _r1.d;
    _r3.d = 10.0D;
    _r1.i = _r1.d > _r3.d ? 1 : (_r1.d == _r3.d ? 0 : -1);
    if (_r1.i < 0) goto label13;
    _r0.i = _r0.i * 10;
    goto label1;
    label13:;
    return _r0.i;
//XMLVM_END_WRAPPER[cz.kruch.track.util.ExtraMath: int grade(double)]
}

public static long round(double n1){
//XMLVM_BEGIN_WRAPPER[cz.kruch.track.util.ExtraMath: long round(double)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r2.d = n1;
    _r0.d = 0.5D;
    _r0.d = _r0.d + _r2.d;
    _r0.d = global::java.lang.Math.floor((double) _r0.d);
    _r0.l = (long) _r0.d;
    return _r0.l;
//XMLVM_END_WRAPPER[cz.kruch.track.util.ExtraMath: long round(double)]
}

public static int round(float n1){
//XMLVM_BEGIN_WRAPPER[cz.kruch.track.util.ExtraMath: int round(float)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r2.f = n1;
    _r0.f = (float)0.5D;
    _r0.f = _r0.f + _r2.f;
    _r0.d = (double) _r0.f;
    _r0.d = global::java.lang.Math.floor((double) _r0.d);
    _r0.i = (int) _r0.d;
    return _r0.i;
//XMLVM_END_WRAPPER[cz.kruch.track.util.ExtraMath: int round(float)]
}

public static double ln(double n1){
    return System.Math.Log(n1);
}

public static double pow(double n1, double n2){
    return System.Math.Pow(n1, n2);
}

public static double powi(double n1, int n2){
//XMLVM_BEGIN_WRAPPER[cz.kruch.track.util.ExtraMath: double powi(double, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r4.d = n1;
    _r6.i = n2;
    _r0.d = 1.0D;
    label2:;
    if (_r6.i <= 0) goto label14;
    _r2.i = _r6.i % 2;
    _r3.i = 1;
    if (_r2.i != _r3.i) goto label10;
    _r0.d = _r0.d * _r4.d;
    label10:;
    _r6.i = _r6.i >> (0x1f & 1);
    _r4.d = _r4.d * _r4.d;
    goto label2;
    label14:;
    return _r0.d;
//XMLVM_END_WRAPPER[cz.kruch.track.util.ExtraMath: double powi(double, int)]
}

public static double atan(double n1){
    return System.Math.Atan(n1);
}

public static double atan2(double n1, double n2){
    return System.Math.Atan2(n1, n2);
}

public static double asin(double n1){
    return System.Math.Asin(n1);
}

public static double acos(double n1){
    return System.Math.Acos(n1);
}

//XMLVM_BEGIN_WRAPPER[cz.kruch.track.util.ExtraMath]
//XMLVM_END_WRAPPER[cz.kruch.track.util.ExtraMath]

} // end of class: ExtraMath

} // end of namespace: cz.kruch.track.util
