//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackingApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really quit?.
        /// </summary>
        public static string AppExitQuestion {
            get {
                return ResourceManager.GetString("AppExitQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrekBuddy.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string CommandDelete {
            get {
                return ResourceManager.GetString("CommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string CommandUpload {
            get {
                return ResourceManager.GetString("CommandUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD synchronization failed: {0}.
        /// </summary>
        public static string MemoryCardSyncFailedMessage {
            get {
                return ResourceManager.GetString("MemoryCardSyncFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing with SD, please wait....
        /// </summary>
        public static string MemoryCardSyncProgress {
            get {
                return ResourceManager.GetString("MemoryCardSyncProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking connectivity....
        /// </summary>
        public static string OneDriveCheckProgress {
            get {
                return ResourceManager.GetString("OneDriveCheckProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file....
        /// </summary>
        public static string OneDriveCopyingFileProgress {
            get {
                return ResourceManager.GetString("OneDriveCopyingFileProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files....
        /// </summary>
        public static string OneDriveCopyingFilesProgress {
            get {
                return ResourceManager.GetString("OneDriveCopyingFilesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create folders on OneDrive if not exist.
        /// </summary>
        public static string OneDriveCreateFolderCheckbox {
            get {
                return ResourceManager.GetString("OneDriveCreateFolderCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}: {1}% ....
        /// </summary>
        public static string OneDriveDownloadingProgressPercent {
            get {
                return ResourceManager.GetString("OneDriveDownloadingProgressPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive initialization failed.
        /// </summary>
        public static string OneDriveInitFailedMessage {
            get {
                return ResourceManager.GetString("OneDriveInitFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing OneDrive folder....
        /// </summary>
        public static string OneDriveListingFolderProgress {
            get {
                return ResourceManager.GetString("OneDriveListingFolderProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed: {0}.
        /// </summary>
        public static string OneDriveLoginFailedMessage {
            get {
                return ResourceManager.GetString("OneDriveLoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive synchronization failed: {0}.
        /// </summary>
        public static string OneDriveSyncFailedMessage {
            get {
                return ResourceManager.GetString("OneDriveSyncFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing with OneDrive, please wait....
        /// </summary>
        public static string OneDriveSyncProgress {
            get {
                return ResourceManager.GetString("OneDriveSyncProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize with OneDrive now?
        ///The following items will be updated from OneDrive:
        /// * resources (resources, sounds)
        /// * waypoints (wpts)
        /// * CMS (ui-profiles).
        /// </summary>
        public static string OneDriveSyncQuestion {
            get {
                return ResourceManager.GetString("OneDriveSyncQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed: {0}.
        /// </summary>
        public static string OneDriveUploadFailedMessage {
            get {
                return ResourceManager.GetString("OneDriveUploadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file....
        /// </summary>
        public static string OneDriveUploadingProgress {
            get {
                return ResourceManager.GetString("OneDriveUploadingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading {0}: {1}% ....
        /// </summary>
        public static string OneDriveUploadingProgressPercent {
            get {
                return ResourceManager.GetString("OneDriveUploadingProgressPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload successful..
        /// </summary>
        public static string OneDriveUploadSuccessMessage {
            get {
                return ResourceManager.GetString("OneDriveUploadSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to device and open it?.
        /// </summary>
        public static string OneDriveUseMapQuestion {
            get {
                return ResourceManager.GetString("OneDriveUseMapQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
